### ISSUE TITLE
Constrained tensors are immutable

### ISSUE THREAD

**Issue by mortonjt** [Lezcano/geotorch#14]
This problem is similar to #13 , but it still appears in the dev version.

Below is a small reproducible example
```python
import torch.nn as nn
import geotorch
class TestModel(nn.Module):
    def __init__(self, inp, out):
        super(TestModel, self).__init__()
        self.linear = nn.Linear(inp, out, bias=False)
        geotorch.grassmannian(self.linear, 'weight')
    def forward(self, x):
        return self.y @ x
    def initialize(self, W):
        self.linear.weight.data = W

model = TestModel(10, 10)
model.initialize(torch.eye(10, 10))
print(model.linear.weight)
```
This will output
```
tensor([[ 0.4076, -0.7197,  0.2221, -0.0862,  0.2790,  0.0037,  0.2593, -0.0412,
          0.2679,  0.2014],
        [ 0.3811,  0.1598, -0.4362,  0.1843,  0.4700,  0.2330,  0.3310,  0.1918,
         -0.2535, -0.3453],
        [ 0.2899,  0.0346,  0.0956, -0.3288,  0.2497, -0.1689, -0.5778,  0.4797,
         -0.3147,  0.2090],
        [-0.4819, -0.2143, -0.1475,  0.4359,  0.4765,  0.2715, -0.3822,  0.0710,
          0.1807,  0.1599],
        [ 0.0939, -0.4457,  0.0543,  0.1005, -0.2818,  0.3427, -0.3295, -0.2776,
         -0.5164, -0.3609],
        [-0.0059,  0.2738,  0.2809, -0.0741,  0.4467,  0.0081,  0.0587, -0.6476,
         -0.3588,  0.2990],
        [ 0.1530, -0.0481, -0.4165, -0.1492,  0.1589, -0.4537, -0.3715, -0.4447,
          0.3176, -0.3330],
        [ 0.0087, -0.1113,  0.1804,  0.6291,  0.0027, -0.6791,  0.0835,  0.0940,
         -0.2826, -0.0490],
        [-0.5572, -0.2248,  0.1368, -0.4524,  0.2850, -0.1927,  0.2348,  0.1440,
         -0.1911, -0.4299],
        [-0.1720, -0.2656, -0.6503, -0.1490, -0.1629, -0.1477,  0.1764, -0.0501,
         -0.3458,  0.5031]], grad_fn=<AliasBackward>)
```
Is it possible to update constrained tensors after constructing the model?

btw, this is such an awesome repository; all of the other components are working beautifully - I'm just testing out different initialization conditions.

EDIT : updated example to showcase this with the identity matrix.

**Comment by Lezcano** [comment]
It is possible, indeed! [Have a look at the examples folder](https://github.com/Lezcano/geotorch/blob/55a91ca973ddeeb12d193d464af4b23da93d5ab4/examples/copying_problem.py#L84). I should add that to the simple example in the `README`.
Long story short, do not assign to the `.data` field, but simply assign to the tensor as
`self.linear.weight = W`

In the `examples` folder you even have a jupyter notebook explaining the implementation details behind the library. In particular, what you are seeing when assigning to the `.data` field (which you should NEVER do in PyTorch, you should prefer `.set_`) is that you are modifying a temporary tensor that is returned by the parametrisation, rather than modifying the parametrisation itself. 

Hope this helps, and glad to know that you find this repo useful!

**Comment by Lezcano** [comment]
In fact, it was already in the first section of the README, but I've made it even more explicit now :)

**Comment by mortonjt** [comment]
_great_ I can confirm that this works.  Thanks!
