### ISSUE TITLE
Upstream Constraints to PyTorch 1.9.X+

### ISSUE THREAD

**Issue by EdwardRaff** [Lezcano/geotorch#21]
Now that PyTorch main stream has the awesome parameterization support you've created, will the constraints like orthogonalization be pushed upstream, or kept separate in this repo? Will the usage change with 1.9 compared to before?

**Comment by Lezcano** [comment]
I can confirm that the parametrizations from GeoTorch work with `torch.nn.utils.parametrize`, as I was who implemented this feature in PyTorch core :)

As it stands `geotorch/parametrize.py` is compatible with the file in PyTorch 1.9. It is not compatible with the one in master as we just merged a few more features that are BC, but I'll update the code soon to account for those changes.

Closing for now, but feel free to reopen if you have more questions, or open a new issue if you find interoperability problems.

**Comment by Lezcano** [comment]
It took some time, but fyi, I just updated geotorch to be fully compatible with the current design of parametrisations in PyTorch master. Even more, if you are using PyTorch 1.10 or newer, GeoTorch uses the system from PyTorch directly so that you can use the functions from `torch.nn.utils.parametrize` to interact with it. 

Even more, I implemented in PyTorch the orthogonal constraints in:
https://pytorch.org/docs/stable/generated/torch.nn.utils.parametrizations.orthogonal.html
If you just want an orthogonal matrix in 1.10 you can use that one rather than the one from GeoTorch. They are very similar, the only difference is that in the one from master you may also use Householder reflectors to parametrise the matrix, and it also supports complex matrices to generate unitary matrices.

**Comment by EdwardRaff** [comment]
Awesome, I really appreciate the update! This has been super useful stuff for me in some of my work, very appreciative :) 

I've also been exploring JAX/FLAX recently, and for customized sequential RNNs been getting huge speedups - you may want to explore that as another option to gift with this really clean design.

**Comment by Lezcano** [comment]
For sequential RNNs, it's true that JAX may be better, as PyTorch just offers fused RNNs with fused activation, which is annoying.

About porting this to JAX, well, I work as a PyTorch core developer, so I think I'll keep supporting the features for PyTorch myself. Now, if someone else wanted to port this to JAX, I think that quite a few people would really appreciate that :)
