### ISSUE TITLE
Error when loading modules with a geotorch constraint

### ISSUE THREAD

**Issue by jeffrey-hokanson** [Lezcano/geotorch#6]
I am having trouble loading networks with geotorch constraints.  The network saves successfully, but when loading I get errors like:

```Can't get attribute 'ParametrizedLinear4551587920' on <module 'geotorch.parametrize' from '/Users/jeffreyh/Library/Python/3.7/lib/python/site-packages/geotorch/parametrize.py'>```

This appears if you run the following example twice: once to save and another time to load.

```python
## Minimal working example
import torch
import geotorch
import os
import tempfile

fname = 'test_jmh.pt'

class Module(torch.nn.Module):
    def __init__(self, constrain = True):
        super(Module, self).__init__()
        self.layer = torch.nn.Linear(10,10)
        if constrain:
            geotorch.orthogonal(self.layer, 'weight')

    def forward(self, x):
        return self.layer.forward(x)

def test_save(constrain = True):
    m = Module(constrain)
    torch.save(m,fname)
    print("saved!")

def test_load():
    m2 = torch.load(fname)
    print("loaded!")

if __name__ == '__main__':
    # The following code runs twice: once to save the file
    # the second time to try to load this file
    if not os.path.isfile(fname):
        test_save(constrain = True)
    else:
        try:
            test_load()
        except Exception as e:
            print(e)

            os.remove(fname)
```

**Comment by Lezcano** [comment]
Uh, that is annoying. Alas, it's not surprising, as parametrisations involve some dynamic class creation, which does not play well with `pickle`, which is what's used behind the scenes by `torch.save`. These problems are circumvented at the moment in a somewhat hacky way [[here](https://github.com/Lezcano/geotorch/blob/master/geotorch/parametrize.py#L154)], which, as you found, can have some rough edges. I will look into this :)

**Comment by Lezcano** [comment]
So, I have pushed a fix into the branch `save`. The only annoying bit is that you have to call `torch.load` and `torch.save` with `dill`, rather than `pickle`. `pickle` not very robust, and it does not play well with dynamically created classes. One can work around that with `dill`. You would have to call the `load` and `save` methods as:

```python
import dill

torch.save(m, fname, pickle_module=dill)
torch.load(fname, pickle_module=dill)
```
Would this work for you?

I will talk with the PyTorch guys, and see if this is acceptable for the PR, for now I'll leave it in the `save` branch.

**Comment by jeffrey-hokanson** [comment]
That fix worked brilliantly!  Thanks so much for responding so quickly.

**Comment by Lezcano** [comment]
Well, thank you for giving a go at `geotorch`! If you have any other comment, suggestion, thing that you would like to see implemented... feel free to open another issue. For now I'm closing this one :)

**Comment by Lezcano** [comment]
When talking with the PyTorch guys about this issue, they told me that it stemmed from loading the whole module, rather than just the `state_dict`s. Even though PyTorch tries its best at saving a module when it's passed to `torch.save`, the recommended way of saving / loading a module goes through using `state_dict` as explained in:
https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training

Parametrisations, when accepted in core PyTorch, they will not support being saved via `torch.save`. In fact, when `torch.load` is called on a parametrised model, will throw an exception pointing the user to that part of the Pytorch tutorials. This will be the only supported way to load / save models in GeoTorch as well. I will update soon the implementation in `master` to reflect all these changes :)
