### ISSUE TITLE
Support float64?

### ISSUE THREAD

**Issue by ahwillia** [Lezcano/geotorch#8]
There is probably a workaround for this, but I can't figure out how to switch from `float32` to `float64`. The following works fine:

```python
import torch
import geotorch
from torch import nn
n = 10
Q = nn.Linear(n, n, bias=False).float()
geotorch.orthogonal(Q, "weight")
Q(torch.ones(10).float())
```

But switching to `double()` causes an error.

```python
import torch
import geotorch
from torch import nn
n = 10
Q = nn.Linear(n, n, bias=False).double()
geotorch.orthogonal(Q, "weight")
Q(torch.ones(10).double())
```

Specifically, 

```
~/.local/lib/python3.8/site-packages/geotorch/so.py in trivialization(self, X)
     58 
     59     def trivialization(self, X):
---> 60         return self.base @ self.triv(X)
     61 
     62     def uniform_init_(self):

RuntimeError: expected scalar type Float but found Double
```

**Comment by Lezcano** [comment]
Registering the constraint adds some buffer, which by default are `float`. Same would happen if you first created the model, then moved it to another device and then put the constraints.
Constraints should be thought as initialisation of the model, as such, the first model should first be initialised and then moved to whichever device and whichever type you need. This being said, your code should be as follows:
```python
import torch
import geotorch
from torch import nn
n = 10
Q = nn.Linear(n, n, bias=False)
geotorch.orthogonal(Q, "weight")
Q = Q.double()
# If you wanted, you could also do so here
Q(torch.ones(10).double())
```
This is how I thought of this originally. On the other hand,  for this not to bite people, I will make so that when you register an orthogonal layer (or any other constraint) the function automatically moves the orthogonal layer to the correct `dtype` and `device`. This should make your original code to work. I'll implement this next week :)

I'll also make that `geotorch.orthogonal` returns the layer so that you can chain operations as:
```python
Q = geotorch.orthogonal(Q, "weight").double()
```

**Comment by Lezcano** [comment]
In fact, it was direct to implement that I just implemented it and it's already merged into master. Your original code should work now. Even then, as a general rule, I would advise you to follow the following pattern:
- Initialise the layers and put the constraints in the corresponding `__init__` methods of your model
- Instantiate your model
- Move your model to the device (cpu/gpu) that you want to use it on and change its `dtype` to whichever `dtype` you want.

**Comment by ahwillia** [comment]
Perfect -- thanks for the quick response and fix!
